### ISSUE TITLE
base config support

### ISSUE THREAD

**Issue by jeffknupp** [appnexus/schema-tool#11]
Right now, the script won't run unless there is a file named `conf.json` in the same directory. Make the name and location of this configurable.

**Comment by JohnMurray** [comment]
I am going to amend / change this a bit to be:

+ Provide a default file-location to put the default config file that is non-configurable (e.g. `~/.schema-tool`)
+ Always load the default configuration if it exists
+ Load local configuration and apply it as a set of "overrides" to the base config

The reason I think this approach is better is because there are some obvious shared configurations (host, password, etc) and there are some very project-specific configurations (database/schema name) and some configurations that may belong in one or the other based on the user's preference / workflow (db type, pre-commit hook, DBA-file generation, etc).
